target = "https://www.rfc-editor.org/rfc/rfc8032#section-5.1.3"

# Decoding
#
#    Decoding a point, given as a 32-octet string, is a little more
#    complicated.
#
#    1.  First, interpret the string as an integer in little-endian
#        representation.  Bit 255 of this number is the least significant
#        bit of the x-coordinate and denote this value x_0.  The
#        y-coordinate is recovered simply by clearing this bit.  If the
#        resulting value is >= p, decoding fails.
#
#    4.  Finally, use the x_0 bit to select the right square root.  If
#        x = 0, and x_0 = 1, decoding fails.  Otherwise, if x_0 != x mod
#        2, set x <-- p - x.  Return the decoded point (x,y).

[[spec]]
level = "MUST"
quote = '''
If the resulting value is >= p, decoding fails.
'''

[[spec]]
level = "MUST"
quote = '''
If x = 0, and x_0 = 1, decoding fails.
'''
