# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR ISC

FROM public.ecr.aws/ubuntu/ubuntu:20.04 AS base

SHELL ["/bin/bash", "-c"]

ENV GOFLAGS=-buildvcs=false
ENV DEBIAN_FRONTEND=noninteractive
ENV ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer

# llvm, llvm-dev, libcxx, and libcxxabi are needed for the sanitizer tests.
# 11.1.0 is the latest stable release as of 2021-02-16.
# See https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo
RUN <<EOF
set -ex
apt-get update
apt-get -y --no-install-recommends upgrade
apt-get -y --no-install-recommends install \
    ca-certificates \
    clang-7 \
    clang-8 \
    clang-9 \
    clang-10 \
    clang-format \
    cmake \
    curl \
    gcc-7 \
    gcc-8 \
    git \
    g++-7 \
    g++-8 \
    libunwind-dev \
    lld \
    llvm \
    llvm-dev \
    perl \
    pkg-config \
    ninja-build \
    software-properties-common \
    unzip \
    wget
apt-get autoremove --purge -y
apt-get clean
apt-get autoclean
rm -rf /var/lib/apt/lists/*
rm -rf /tmp/*
EOF

FROM base AS tools

# Create compiler environment setup scripts
COPY --from=scripts create-compiler-env.sh /tmp
RUN <<EOF
set -ex
setup_script="/tmp/create-compiler-env.sh"
${setup_script}
EOF

# Install AWS CLI
COPY --from=scripts setup-aws-cli.sh /tmp
RUN <<EOF
set -ex
setup_script="/tmp/setup-aws-cli.sh"
${setup_script}
EOF

# Install Go
ENV GOENV_ROOT="/.goenv"
ENV PATH="${GOENV_ROOT}/shims:${GOENV_ROOT}/bin:/go/bin:$PATH"

COPY --from=scripts setup-go-compiler.sh /tmp
RUN <<EOF
setup_script="/tmp/setup-go-compiler.sh"
${setup_script}
EOF

RUN rm -rf /tmp/*
