# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR ISC

FROM ubuntu:10.04 AS base

CMD ["/bin/bash"]

# The following hack is to avoid a problem where glibc update fails b/c kernel revision is >255
# https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1962225
RUN mv /bin/uname /bin/uname.orig
RUN printf '#!/bin/bash\n\nif [[ "$1" == "-r" ]] ;then\n echo '4.9.250'\n exit\nelse\n uname.orig "$@"\nfi' > /bin/uname
RUN chmod 755 /bin/uname

RUN <<EOF
sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
apt-get update
apt-get -y --no-install-recommends install \
    gcc-4.1 \
    g++-4.1 \
    make
perl
EOF

# Pull cmake as an external source since the wget version
# on this image is too old to access the cmake repo.
COPY --from=dependencies cmake-3.9.6.tar.gz /tmp/cmake-3.9.6.tar.gz
RUN <<EOF
cd /tmp
tar -xvf cmake-3.9.6.tar.gz
cd cmake-3.9.6
env CC=gcc-4.1 \
    CXX=g++-4.1 \
    ./configure
make
make install
rm -rf /tmp/*
EOF

FROM base AS tools

# Create compiler environment setup scripts
COPY --from=scripts create-compiler-env.sh /tmp
RUN <<EOF
set -ex
setup_script="/tmp/create-compiler-env.sh"
${setup_script}
EOF

# Install Rust
#
# This image is pinned to Rust 1.63.0, the last release whose binaries run
# against glibc older than 2.17 (1.64.0 raised the tier-1 *-unknown-linux-gnu
# baseline). It also cannot use rustup, since rustup-init itself requires
# glibc 2.17. The tarball is fetched on the runner and supplied through the
# dependencies build context because this image's TLS stack is too old to reach
# static.rust-lang.org, the same reason CMake is sourced that way above.
ENV CARGO_HOME="/.cargo"

COPY --from=dependencies rust-1.63.0-x86_64-unknown-linux-gnu.tar.gz /tmp/rust-1.63.0-x86_64-unknown-linux-gnu.tar.gz
COPY --from=scripts setup-rust-standalone.sh /tmp
RUN <<EOF
set -ex
setup_script="/tmp/setup-rust-standalone.sh"
${setup_script} /tmp/rust-1.63.0-x86_64-unknown-linux-gnu.tar.gz
EOF

RUN rm -rf /tmp/*
