#!/usr/bin/env python3
# Generate Keccak-256 known-answer test (KAT) vectors for AWS-LC.
#
# Mirrors the format used by NIST SHA-3 KATs (Len, Msg, MD per record). Inputs
# are pseudorandom but deterministic (fixed SHAKE128 seed). Outputs come from
# pycryptodome's keccak.new(digest_bits=256), which is the original-padding
# Keccak-256 used by Ethereum.
#
# Requires pycryptodome. Set up and run with:
#
#     python3 -m venv /tmp/keccak_venv
#     /tmp/keccak_venv/bin/pip install pycryptodome
#     /tmp/keccak_venv/bin/python util/gen_keccak256_kat.py
#
# By design, the reference (pycryptodome) and the implementation under test
# (AWS-LC) come from completely different code, so the test asserts genuine
# cross-implementation agreement rather than self-consistency.
#
# Two output files mirror the SHA-3 KAT layout:
#   KECCAK_256ShortMsg.txt: byte-aligned lengths from 0 to 1088 bits (rate
#       boundary).
#   KECCAK_256LongMsg.txt:  multi-block lengths from 2184 to 110688 bits, in
#       1096-bit steps.

import hashlib
import os
import sys

from Crypto.Hash import keccak


def keccak256(data: bytes) -> bytes:
    h = keccak.new(digest_bits=256)
    h.update(data)
    return h.digest()


def deterministic_bytes(n):
    # SHAKE128 of a fixed seed gives reproducible pseudorandom bytes. SHAKE128
    # is from the Python standard library and is not the function under test.
    return hashlib.shake_128(b'aws-lc keccak-256 KAT seed').digest(n)


def write_kat(path, bit_lens, header_note):
    with open(path, 'w') as f:
        f.write('# Keccak-256 known-answer test vectors.\n')
        f.write('# Generated by util/gen_keccak256_kat.py.\n')
        f.write('# Inputs are deterministic SHAKE128 expansions of a fixed seed.\n')
        f.write('# Outputs are computed by pycryptodome (Crypto.Hash.keccak).\n')
        f.write(f'# {header_note}\n')
        f.write('#\n')
        f.write('# Format: Len is the message length in BITS (multiple of 8).\n')
        f.write('#         Msg is the message in lowercase hex (or "00" when Len = 0,\n')
        f.write('#         to match the SHA-3 KAT convention).\n')
        f.write('#         MD is the 256-bit Keccak-256 digest in lowercase hex.\n')
        f.write('\n')
        for bit_len in bit_lens:
            assert bit_len % 8 == 0, 'Only byte-aligned vectors supported'
            byte_len = bit_len // 8
            msg = deterministic_bytes(byte_len)
            md = keccak256(msg)
            f.write(f'Len = {bit_len}\n')
            f.write('Msg = ' + ('00' if byte_len == 0 else msg.hex()) + '\n')
            f.write(f'MD = {md.hex()}\n')
            f.write('\n')


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else (
        os.path.join(os.path.dirname(__file__), '..', 'crypto', 'keccak',
                     'testvectors'))
    out_dir = os.path.normpath(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    # Sanity check pycryptodome's output against the well-known Ethereum
    # Keccak-256 values (publicly documented in the Ethereum Yellow Paper,
    # Solidity docs, eth_utils, etc.). If any of these don't match, abort.
    sanity = [
        (b'', 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'),
        (b'abc', '4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45'),
        (b'The quick brown fox jumps over the lazy dog',
         '4d741b6f1eb29cb2a9b9911c82f56fa8d73b04959d3d9d222895df6c0b28aa15'),
    ]
    for msg, expected in sanity:
        got = keccak256(msg).hex()
        if got != expected:
            sys.exit(f'pycryptodome sanity check failed for {msg!r}: '
                     f'got {got}, want {expected}')

    short_lens = list(range(0, 1089, 8))
    write_kat(os.path.join(out_dir, 'KECCAK_256ShortMsg.txt'),
              short_lens,
              'ShortMsg: byte-aligned lengths 0..1088 bits.')

    long_lens = list(range(2184, 110689, 1096))
    write_kat(os.path.join(out_dir, 'KECCAK_256LongMsg.txt'),
              long_lens,
              'LongMsg: multi-block lengths 2184..110688 bits, step 1096 bits.')

    print(f'Wrote {len(short_lens)} short vectors and {len(long_lens)} long '
          f'vectors to {out_dir}')


if __name__ == '__main__':
    main()
