if(WIN32 OR UNIX OR APPLE)
    find_package(Threads REQUIRED)
endif()

# Allow static or shared lib to be used.
# If both are installed, choose based on BUILD_SHARED_LIBS.
if (BUILD_SHARED_LIBS)
    if (EXISTS "${CMAKE_CURRENT_LIST_DIR}/shared/crypto-targets.cmake")
        message(STATUS "FOUND AWS-LC CRYPTO cmake config - shared")
        include(${CMAKE_CURRENT_LIST_DIR}/shared/crypto-targets.cmake)
    else()
        message(STATUS "FOUND AWS-LC CRYPTO cmake config - static")
        include(${CMAKE_CURRENT_LIST_DIR}/static/crypto-targets.cmake)
    endif()
else()
    if (EXISTS "${CMAKE_CURRENT_LIST_DIR}/static/crypto-targets.cmake")
        message(STATUS "FOUND AWS-LC CRYPTO cmake config - static")
        include(${CMAKE_CURRENT_LIST_DIR}/static/crypto-targets.cmake)
    else()
        message(STATUS "FOUND AWS-LC CRYPTO cmake config - shared")
        include(${CMAKE_CURRENT_LIST_DIR}/shared/crypto-targets.cmake)
    endif()
endif()
