name: ABI Diff
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
env:
  DOCKER_BUILDKIT: 1
  GOPROXY: https://proxy.golang.org,direct
jobs:
  libs:
    if: github.repository_owner == 'aws'
    name: libcrypto and libssl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: aws/aws-lc
          ref: ${{ github.event_name == 'push' && github.event.ref || github.event.pull_request.head.sha }}
          path: ${{ github.workspace }}/next
      - uses: actions/checkout@v3
        with:
          repository: aws/aws-lc
          ref: ${{ github.event_name == 'push' && github.event.before || github.event.pull_request.base.sha }}
          path: ${{ github.workspace }}/previous
      - name: Build Docker Image
        working-directory: ${{ github.workspace }}/next/.github/docker_images/abidiff
        run: |
          docker build -t abidiff .
      - name: Perform libcrypto ABI Diff
        run: |
          docker run -v ${{ github.workspace }}/previous:/previous -v ${{ github.workspace }}/next:/next abidiff crypto
      - name: Perform libssl ABI Diff
        if: ${{ success() || failure() }}
        run: |
          docker run -v ${{ github.workspace }}/previous:/previous -v ${{ github.workspace }}/next:/next abidiff ssl
