name: image-build-ubuntu2204
on:
  workflow_call:
    inputs:
      concurrency_prefix:
        default: image-build-ubuntu2204
        required: false
        type: string
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/docker_images/aws-lc/ubuntu/Dockerfile.2204
      - .github/docker_images/scripts/**
  pull_request:
    branches: [main]
    paths:
      - .github/docker_images/aws-lc/ubuntu/Dockerfile.2204
      - .github/docker_images/scripts/**
concurrency:
  group: ${{ inputs.concurrency_prefix || github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
env:
  GOPROXY: https://proxy.golang.org,direct
  DOCKER_BUILD_RECORD_UPLOAD: false
jobs:
  x86_64_build:
    runs-on:
      codebuild-aws-lc-github-docker-image-build-${{ github.run_id }}-${{ github.run_attempt }}
      image:linux-5.0
      instance-size:small
    outputs:
      ubuntu2204: ${{ steps.images.outputs.ubuntu2204 }}
      ubuntu2204_sde: ${{ steps.images.outputs.ubuntu2204_sde }}
    steps:
      - uses: actions/checkout@v5
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get ECR Registry & Repository Details
        id: ecr
        run: |
          echo staging_url=${ECR_STAGING_REPO} >> "$GITHUB_OUTPUT"
      - name: Generate Staging Image Names
        id: images
        run: |
          echo ubuntu2204=${{ steps.ecr.outputs.staging_url }}:$(uuidgen) >> "$GITHUB_OUTPUT"
          echo ubuntu2204_sde=${{ steps.ecr.outputs.staging_url }}:$(uuidgen) >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          file: ./.github/docker_images/aws-lc/ubuntu/Dockerfile.2204
          context: ./.github/docker_images/aws-lc/ubuntu
          build-contexts: |
            scripts=./.github/docker_images/scripts
          target: ubuntu2204
          tags: ${{ steps.images.outputs.ubuntu2204 }}
          push: true
      - uses: docker/build-push-action@v6
        with:
          file: ./.github/docker_images/aws-lc/ubuntu/Dockerfile.2204
          context: ./.github/docker_images/aws-lc/ubuntu
          build-contexts: |
            scripts=./.github/docker_images/scripts
          target: ubuntu2204_sde
          tags: ${{ steps.images.outputs.ubuntu2204_sde }}
          push: true
      - uses: ./.github/actions/codebuild-docker-run
        name: Validate Container (ubuntu2204)
        with:
          image: ${{ steps.images.outputs.ubuntu2204 }}
          run: |
            ./.github/docker_images/scripts/verify-aws-cli-version.sh 2
            ./.github/docker_images/scripts/verify-go-version.sh 1.25
            ./.github/docker_images/scripts/verify-cmake-version.sh cmake 3.22
            ./.github/docker_images/scripts/verify-perl-version.sh 5.34
            # Check GCC Default Compilers
            source /opt/compiler-env/setup-gcc.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 11.4
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 11.4
            # Check GCC 10 Compilers
            source /opt/compiler-env/setup-gcc-10.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 10.5
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 10.5
            # Check GCC 11 Compilers
            source /opt/compiler-env/setup-gcc-11.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 11.4
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 11.4
            # Check GCC 12 Compilers
            source /opt/compiler-env/setup-gcc-12.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 12.3
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 12.3
            # Check Clang 14 Compilers
            source /opt/compiler-env/setup-clang-14.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC clang 14.0
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX clang 14.0
      - uses: ./.github/actions/codebuild-docker-run
        name: Validate Container (ubuntu2204_sde)
        with:
          image: ${{ steps.images.outputs.ubuntu2204_sde }}
          run: |
            ./.github/docker_images/scripts/verify-aws-cli-version.sh 2
            ./.github/docker_images/scripts/verify-go-version.sh 1.25
            ./.github/docker_images/scripts/verify-cmake-version.sh cmake 3.22
            ./.github/docker_images/scripts/verify-perl-version.sh 5.34
            # Check GCC Default Compilers
            source /opt/compiler-env/setup-gcc.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 11.4
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 11.4
            # Check GCC 10 Compilers
            source /opt/compiler-env/setup-gcc-10.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 10.5
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 10.5
            # Check GCC 11 Compilers
            source /opt/compiler-env/setup-gcc-11.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 11.4
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 11.4
            # Check GCC 12 Compilers
            source /opt/compiler-env/setup-gcc-12.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 12.3
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 12.3
            # Check Clang 14 Compilers
            source /opt/compiler-env/setup-clang-14.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC clang 14.0
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX clang 14.0
            sde --version | grep 9.44

  x86_64_push:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on:
      codebuild-aws-lc-github-docker-image-build-${{ github.run_id }}-${{ github.run_attempt }}
      image:linux-5.0
      instance-size:small
    needs:
      - x86_64_build
    outputs:
      ubuntu2204: ${{ steps.images.outputs.ubuntu2204 }}
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get ECR Registry & Repository Details
        id: ecr
        run: |
          echo registry_url=${ECR_REGISTRY_URL} >> "$GITHUB_OUTPUT"
      - name: Generate Staging Image Names
        id: images
        run: |
          echo ubuntu2204=${{ steps.ecr.outputs.registry_url }}/aws-lc/ubuntu:22.04_x86_64 >> "$GITHUB_OUTPUT"
          echo ubuntu2204_sde=${{ steps.ecr.outputs.registry_url }}/aws-lc/ubuntu:22.04_sde >> "$GITHUB_OUTPUT"
      - name: Pull Images From Staging
        run: |
          docker pull ${{ needs.x86_64_build.outputs.ubuntu2204 }}
          docker pull ${{ needs.x86_64_build.outputs.ubuntu2204_sde }}
      - name: Tag Images
        run: |
          docker tag ${{ needs.x86_64_build.outputs.ubuntu2204 }} ${{ steps.images.outputs.ubuntu2204 }}
          docker tag ${{ needs.x86_64_build.outputs.ubuntu2204_sde }} ${{ steps.images.outputs.ubuntu2204_sde }}
      - name: Push Images
        run: |
          docker push ${{ steps.images.outputs.ubuntu2204 }}
          docker push ${{ steps.images.outputs.ubuntu2204_sde }}

  aarch64_build:
    runs-on:
      codebuild-aws-lc-github-docker-image-build-${{ github.run_id }}-${{ github.run_attempt }}
      image:arm-3.0
      instance-size:small
    outputs:
      ubuntu2204: ${{ steps.images.outputs.ubuntu2204 }}
    steps:
      - uses: actions/checkout@v5
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get ECR Registry & Repository Details
        id: ecr
        run: |
          echo staging_url=${ECR_STAGING_REPO} >> "$GITHUB_OUTPUT"
      - name: Generate Staging Image Names
        id: images
        run: |
          echo ubuntu2204=${{ steps.ecr.outputs.staging_url }}:$(uuidgen) >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          file: ./.github/docker_images/aws-lc/ubuntu/Dockerfile.2204
          context: ./.github/docker_images/aws-lc/ubuntu
          build-contexts: |
            scripts=./.github/docker_images/scripts
          target: ubuntu2204
          tags: ${{ steps.images.outputs.ubuntu2204 }}
          push: true
      - uses: ./.github/actions/codebuild-docker-run
        name: Validate Container
        with:
          image: ${{ steps.images.outputs.ubuntu2204 }}
          run: |
            ./.github/docker_images/scripts/verify-aws-cli-version.sh 2
            ./.github/docker_images/scripts/verify-go-version.sh 1.25
            ./.github/docker_images/scripts/verify-cmake-version.sh cmake 3.22
            ./.github/docker_images/scripts/verify-perl-version.sh 5.34
            # Check GCC Default Compilers
            source /opt/compiler-env/setup-gcc.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 11.4
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 11.4
            # Check GCC 10 Compilers
            source /opt/compiler-env/setup-gcc-10.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 10.5
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 10.5
            # Check GCC 11 Compilers
            source /opt/compiler-env/setup-gcc-11.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 11.4
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 11.4
            # Check GCC 12 Compilers
            source /opt/compiler-env/setup-gcc-12.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC gcc 12.3
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX g++ 12.3
            # Check Clang 14 Compilers
            source /opt/compiler-env/setup-clang-14.sh
            ./.github/docker_images/scripts/verify-compiler-version.sh $CC clang 14.0
            ./.github/docker_images/scripts/verify-compiler-version.sh $CXX clang 14.0

  aarch64_push:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on:
      codebuild-aws-lc-github-docker-image-build-${{ github.run_id }}-${{ github.run_attempt }}
      image:arm-3.0
      instance-size:small
    needs:
      - aarch64_build
    outputs:
      ubuntu2204: ${{ steps.images.outputs.ubuntu2204 }}
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get ECR Registry & Repository Details
        id: ecr
        run: |
          echo registry_url=${ECR_REGISTRY_URL} >> "$GITHUB_OUTPUT"
      - name: Generate Staging Image Names
        id: images
        run: |
          echo ubuntu2204=${{ steps.ecr.outputs.registry_url }}/aws-lc/ubuntu:22.04_aarch64 >> "$GITHUB_OUTPUT"
      - name: Pull Images From Staging
        run: |
          docker pull ${{ needs.aarch64_build.outputs.ubuntu2204 }}
      - name: Tag Images
        run: |
          docker tag ${{ needs.aarch64_build.outputs.ubuntu2204 }} ${{ steps.images.outputs.ubuntu2204 }}
      - name: Push Images
        run: |
          docker push ${{ steps.images.outputs.ubuntu2204 }}

  multiarch_manifest:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on:
      codebuild-aws-lc-github-docker-image-build-${{ github.run_id }}-${{ github.run_attempt }}
      image:linux-5.0
      instance-size:small
    needs:
      - x86_64_push
      - aarch64_push
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get ECR Registry & Repository Details
        id: ecr
        run: |
          echo registry_url=${ECR_REGISTRY_URL} >> "$GITHUB_OUTPUT"
      - name: Generate Manifest Name
        id: images
        run: |
          echo ubuntu2204=${{ steps.ecr.outputs.registry_url }}/aws-lc/ubuntu:22.04 >> "$GITHUB_OUTPUT"
      - name: Create & Push Multi-platform Manifests
        run: |
          docker manifest create ${{ steps.images.outputs.ubuntu2204 }} \
            ${{ needs.x86_64_push.outputs.ubuntu2204 }} \
            ${{ needs.aarch64_push.outputs.ubuntu2204 }}
      - name: Push Multi-platform manifests
        run: |
          docker manifest push ${{ steps.images.outputs.ubuntu2204 }}
