name: OpenSSL CLI Comparison Tests
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  openssl_comparison_tests:
    if: github.repository_owner == 'aws'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install OS Dependencies
        run: |
          sudo apt-get update -o Acquire::Languages=none -o Acquire::Translation=none
          sudo apt-get -y --no-install-recommends install \
            cmake clang ninja-build golang make autoconf pkg-config openssl
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      - name: Build AWS-LC & OpenSSL and Run Comparison Tests
        run: |
            ./tests/ci/run_openssl_comparison_tests.sh
